### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Kydesn1k** [darkjacky/pwnscripthook#2]
how to setup ? I simply ignores scripthook all addons on my server is still available for download

**Comment by darkjacky** [comment]
Download, put in a folder with a name of your liking and put it in the addons folder on your server.

**Comment by Kydesn1k** [comment]
in the code do not need to edit? just throw pwnscripthook-master in the addons folder and edit anything in it is not necessary?

**Comment by darkjacky** [comment]
Yep thats all no need to edit.
The addon disables scripthook and overwrites all already stolen files

**Comment by Kydesn1k** [comment]
He don't work on local server? Because I'll check this addon, and you can still steal all files

**Comment by darkjacky** [comment]
it indeed does not work on localhost

**Comment by Kydesn1k** [comment]
ok, thank you
